### ISSUE TITLE
如果字段名称包含@符号会报错

### ISSUE THREAD

**Issue by xuanyuan1hao** [Anonymity94/spl2dsl#1]
你好，我这里使用@timestamp='2022-01-01' 作为转换条件，转换会报错。

**Comment by Anonymity94** [comment]
@xuanyuan1hao 好的，我定位下问题，今天给处理下。^_^

**Comment by Anonymity94** [comment]
@xuanyuan1hao 你好，问题已经解决~前缀符号除了支持 @ 外，还可以支持 下划线 _
