### ISSUE TITLE
value值如果带有等号的话会出错

### ISSUE THREAD

**Issue by xuanyuan1hao** [Anonymity94/spl2dsl#4]
你好，我这里测试使用如下语句，解析不了。

service_id='a=1'

**Comment by Anonymity94** [comment]
@xuanyuan1hao 你好，目前 value 中中只允许输入大小字母、数字、下划线[_]、英文的点[.]、冒号[:]、正斜杠[/]、通配符[*]、通配符[?]，如果有需要我可以给添加上 =。这些规则限制可以在 README 中查看。

**Comment by Anonymity94** [comment]
已解决。

**Comment by xuanyuan1hao** [comment]
谢谢，这种等号，下划线，大于号，小于号在内容中出现的概率还是挺高的。

**Comment by Anonymity94** [comment]
@xuanyuan1hao 好的。我下午都给加上~
